import './globals.css'
import { Inter } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry';

import { __APP_NAME__ } from '@/lib/constants';
import Providers from './providers';
import { getSession } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: __APP_NAME__,
  description: 'Generated by @najathi',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  )
}
